### ISSUE TITLE
Cool things, but what about render data from DB?

### ISSUE THREAD

**Issue by ruslankonev** [xpepermint/vue-cli-template#1]
Hey, cool repo's, but what you think about integrate backend datas — pass data from back databases (Mongo/Mysql/other) to vue components, such as jade/pug render options? And how it realize without compile to frontend bundle?

**Comment by xpepermint** [comment]
I use [vuex](https://vuex.vuejs.org/en/intro.html). Would you like me to include a tutorial on that as par of a template?

**Comment by ruslankonev** [comment]
Yes, please

**Comment by xpepermint** [comment]
I created a book [Vue.js Cheatsheet](https://xpepermint.gitbooks.io/vue-js-cheatsheet/content/) where you'll find all the details. The link has also been added in the readme.
