### ISSUE TITLE
Use vue-router & vue-meta

### ISSUE THREAD

**Issue by CDuane** [xpepermint/vue-cli-template#10]
Hi, I am new to Vue.js and am struggling to connect vue-router and vue-meta to this template. Can anyone please point me in the right direction?

The problem I am having is only SSR related: "I get a window is not defined" error.

Thanks!

**Comment by xpepermint** [comment]
Hey. This should be super easy. Just follow the [vue-example](https://github.com/xpepermint/vue-example). 

The error says that you are using `window` on the server. Router works because I use it, so maybe the issue is with `vue-meta` - just guessing.
