### ISSUE TITLE
Webpack bundling missing

### ISSUE THREAD

**Issue by bernardocs** [xpepermint/vue-cli-template#2]
Hey guys...

I'm hyped to use this project as a template to make a service that renders `.vue` files as String.

I followed the instructions (easy... `vue init` and then `npm install` and then `npm run start`) but I got:
```
[project path]/src/scripts/start.js:1
(function (exports, require, module, __filename, __dirname) { const {Server} = require('..');
                                                                    ^
SyntaxError: Unexpected token {
```

Typical error when I got a JS file with ES6 syntax and tried to run it without passing throught Babel (webpack). And, indeed, I didn't see any Webpack output on the terminal.

In fact... I saw `webpack` on `package.json` as a dev dependency. But I didn't saw any `webpack.config.js` file.

I think we're supposed to assign `vue-webpack` object to the hypothetical file `webpack.config.js`.
Or am I missing something? 🤔

**Comment by bernardocs** [comment]
Figured that out... Need Node v6+
I've updated to the current stable version (v7.0.0) and things went smoothly. 😃

**Comment by xpepermint** [comment]
You can downgrade your code if you want.

So, there is no need for the `webpack.config.js`, this package uses [vue-webpack](https://github.com/xpepermint/vue-webpack) instead. That's much easier and makes your code clean. The `vue-webpack` ensures that you have the latest tools for the `Vue.js` project - it builds a common `vue.js` webpack configuration file. But then again, you can replace this shortcut with your own `webpack.config.js`.

I will add a note about node version in the doc. Thx ...
