### ISSUE TITLE
Which component to render based on route param

### ISSUE THREAD

**Issue by bernardocs** [xpepermint/vue-cli-template#4]
Hey guys... it's me again.. Hahaha

I've been trying to make Express route `/templates/{id}`. And depending on the `id` param I'll render a different component.

There's any way, using the project structure, you guys thought on how to route with this kind of mindset?

I'm a bit lost in this structure... 🤔

**Comment by xpepermint** [comment]
Hey, @bernardocs. This project is a template for [vue-cli](https://github.com/vuejs/vue-cli). You should follow the instructions from the readme.

```
$ npm install -g vue-cli
$ vue init xpepermint/vue-cli-template my-project
$ cd my-project
$ npm install
$ npm run start
```

The command-line commands above will create a new project folder `my-project`, install the required dependencies and start the HTTP server.

**Comment by xpepermint** [comment]
After you install the project as explained, see the tutorial on how to [setup a router](https://xpepermint.gitbooks.io/vue-js-cheatsheet/content/navigation_using_router.html). This template only initializes a new Vue.js application which is rendered server-side and client-side. You then build your application on top of this. [Vue.js Cheatsheet](https://xpepermint.gitbooks.io/vue-js-cheatsheet/content/) should give you all you need .
If you need to extend the `express` server, then you should do this [here](https://github.com/xpepermint/vue-cli-template/tree/master/template/src/server).

**Comment by bernardocs** [comment]
Got it 👍 

Thanks again.
